name: CI

# trigger
on:
  push:
    branches:
    - main
  pull_request:
  schedule:
    # run Tuesday and Friday at 02:00 UTC
    - cron: '00 2 * * TUE,FRI'

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test on latest and minimum python version
        python-version: ['3.10', '3.8']

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Prepare python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~ /.cache
        key: ci-${{ runner.os }}-${{ matrix.python-version }}-base

    - name: Install dependencies
      run: pip install -r requirements_dev.txt

    # TODO remove once released
    - name: Install custom libpetab-python
      run: |
        pip install --upgrade --upgrade-strategy eager -e git+https://github.com/PEtab-dev/libpetab-python.git@develop#egg=petab

    - name: Run tox
      run: python -m tox
